### ISSUE TITLE
[SUPPORT] - Problems with a client connecting to a 5.0.0 server. 

### ISSUE THREAD

**Issue by miverson** [paramiko/paramiko#2608]
### Are you using paramiko as a client or server?

Server

### What feature(s) aren't working right?

Keys/auth

### What version(s) of paramiko are you using?

5.0,0

### What version(s) of Python are you using?

pypy 3.11

### What operating system and version are you using?

Kubernetes

### What are you trying to do with paramiko?

I'm having problems with a client that is failing to connect to my server. My host key (ssh-rsa) is as SHA256 signed. My host key is as follows:

"2048 SHA256:-deleted- postmaster@-deleted-.com (RSA)"

This should be of sufficient length to be compatible with Paramiko 5.0.0. It also is signed with an appropriate signature algorithm. 

### How are you trying to do it, and what's happening instead?

However, connection attempts from a client are failing. Here is the debug output:

> sshd.py:transport.py:1786 DEBUG Local version/idstring: SSH-2.0-paramiko_5.0.0
> sshd.py:transport.py:1786 DEBUG Remote version/idstring: SSH-2.0-WS_FTP-12.9.2-0
> sshd.py:transport.py:1786 INFO Connected (version 2.0, client WS_FTP-12.9.2-0)
> sshd.py:transport.py:1786 DEBUG === Key exchange possibilities ===
> sshd.py:transport.py:1786 DEBUG kex algos: diffie-hellman-group-exchange-sha256, diffie-hellman-group-exchange-sha1, diffie-hellman-group14-sha1, diffie-hellman-group1-sha1
> sshd.py:transport.py:1786 DEBUG server key: ssh-dss, ssh-rsa
> sshd.py:transport.py:1786 DEBUG client encrypt: aes256-ctr, aes192-ctr, aes128-ctr, aes256-cbc, 3des-cbc, aes192-cbc, aes128-cbc, blowfish-cbc
> sshd.py:transport.py:1786 DEBUG server encrypt: aes256-ctr, aes192-ctr, aes128-ctr, aes256-cbc, 3des-cbc, aes192-cbc, aes128-cbc, blowfish-cbc
> sshd.py:transport.py:1786 DEBUG client mac: hmac-sha2-512, hmac-sha2-384, hmac-sha2-256, hmac-sha1, hmac-md5, hmac-ripemd160
> sshd.py:transport.py:1786 DEBUG server mac: hmac-sha2-512, hmac-sha2-384, hmac-sha2-256, hmac-sha1, hmac-md5, hmac-ripemd160
> sshd.py:transport.py:1786 DEBUG client compress: zlib, none
> sshd.py:transport.py:1786 DEBUG server compress: zlib, none
> sshd.py:transport.py:1786 DEBUG client lang: <none>
> sshd.py:transport.py:1786 DEBUG server lang: <none>
> sshd.py:transport.py:1786 DEBUG kex follows: False
> sshd.py:transport.py:1786 DEBUG === Key exchange agreements ===
> sshd.py:transport.py:1786 DEBUG Kex: diffie-hellman-group-exchange-sha256
> sshd.py:transport.py:1786 ERROR Exception (server): Incompatible ssh peer (no acceptable host key)
> sshd.py:transport.py:1784 ERROR Traceback (most recent call last):
> sshd.py:transport.py:1784 ERROR File "/opt/pypy/lib/pypy3.11/site-packages/paramiko/transport.py", line 2080, in run
> sshd.py:transport.py:1784 ERROR self._handler_table[ptype](m)
> sshd.py:transport.py:1784 ERROR File "/opt/pypy/lib/pypy3.11/site-packages/paramiko/transport.py", line 2200, in _negotiate_keys
> sshd.py:transport.py:1784 ERROR self._parse_kex_init(m)
> sshd.py:transport.py:1784 ERROR ^^^^^^^^^^^^^^^
> sshd.py:transport.py:1784 ERROR File "/opt/pypy/lib/pypy3.11/site-packages/paramiko/transport.py", line 2451, in _parse_kex_init
> sshd.py:transport.py:1784 ERROR raise IncompatiblePeer(
> sshd.py:transport.py:1784 ERROR paramiko.ssh_exception.IncompatiblePeer: Incompatible ssh peer (no acceptable host key) 

I have read the blurb in the release:

> [Support]: Removed support for verifying/signing with RSA keys using SHA-1 hashing. Generally, this means most cases where "ssh-rsa" was used as an algorithm identifier (as opposed to a key material identifier) will no longer accept that string as valid, and the relevant code that actually used eg hashes.SHA1 no longer does.

My question is, am I doing something wrong? The client (according to the version string) should support sha256 RSA keys. If anyone has any insight on anything I can change to migrate to >=5.0.0 it would be appreciated. The same keys work fine in 4.0.0. I want to rule out any mistakes/improper setup on my part. 

### Anything else?

The host keys are loaded with this code:

```
    server = SSHServer((HOST, PORT),
                           [paramiko.RSAKey.from_private_key_file('/etc/host-keys/ssh-host-rsa-key'),
                            #paramiko.DSSKey.from_private_key_file('/etc/host-keys/ssh-host-dsa-key'),
                            paramiko.ECDSAKey.from_private_key_file('/etc/host-keys/ssh-host-ecdsa-key'),
                            paramiko.Ed25519Key.from_private_key_file('/etc/host-keys/ssh-host-ed25519-key')],
                           SSHRequestHandler)
```

**Comment by miverson** [comment]
Could this be related to the recent comment in #2126?

**Comment by miverson** [comment]
I have diagnosed my issue, and it is with the client, not the paramiko server. 

The client only supports 'ssh-dss' and 'ssh-rsa' host key algorithms, due to a configuration problem with WS_SFTP. (Linked [here for reference](https://community.progress.com/s/article/Supported-SSH-Algo-s) should anyone have the same problem and stumble upon this in the future. 

I had initially thought that the server was advertising these algorithms, but that proved to be a misinterpretation of the "server key" debug messages, which show the client side algorithms used to validate the server's host key. a little instrumentation of the error message in transport.py identified the problem.

**Comment by bitprophet** [comment]
Thanks for the followup, glad you figured it out!

The log message seems to be "technically correct" in the sense that it's displaying the _other end_'s advertisement of what _it_ supports, and so here, that line is about what host/server key algorithms the client supports. Agree it's not obvious from context unless you're aware of exactly this log section is about (displaying a packet from the remote end).

I'm curious if changing it to read `host key` would have clued you in sooner, since that's where my brain goes when I read this (very, very old, it also says things like `encrypt` where OpenSSH says `cipher`) code section.

Maybe only in tandem with upgrading the `=== Key exchange possibilities ===` line before that set of log lines, to include a reminder that the log is from server or client side? Eg, `=== Key exchange options offered by connecting client ===` (when in server mode) and `=== Key exchange options offered by target server ===` (when in client mode)?

**Comment by miverson** [comment]
> I'm curious if changing it to read host key would have clued you in sooner

I would tend to think a touch of disambiguation of the messages would have helped me in this case. The negotiation process elsewhere clearly states "server" and "client" to delineate each side of the negotiation, and having that be crystal clear may be beneficial. 

I resolved the issue in this case by explaining it in the support ticket, which lead me to stop obsessing over it long enough to think differently about the problem, which in turn lead to me add some logging to transport.py, and I identified client software as being the source of the problem. 

So, yes, your suggestion is a good idea, at least for my flawed brain.
