### PR TITLE
Ed25519Key fixes

### LINKED ISSUE #990: bcrypt dependency version should be 3.1.3
Earlier versions don't support `ignore_few_rounds` parameter for `kdf()`:
```
$ /usr/bin/python2 ./test.py --no-sftp --no-big-file
............................................................................E...............................................................................
======================================================================
ERROR: test_ed25519 (tests.test_pkey.KeyTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/paramiko-2.2.0/tests/test_pkey.py", line 456, in test_ed25519
    test_path('test_ed25519_password.key'), b'abc123'
  File "/builddir/build/BUILD/paramiko-2.2.0/paramiko/pkey.py", line 205, in from_private_key_file
    key = cls(filename=filename, password=password)
  File "/builddir/build/BUILD/paramiko-2.2.0/paramiko/ed25519key.py", line 59, in __init__
    signing_key = self._parse_signing_key_data(data, password)
  File "/builddir/build/BUILD/paramiko-2.2.0/paramiko/ed25519key.py", line 122, in _parse_signing_key_data
    ignore_few_rounds=True,
TypeError: kdf() got an unexpected keyword argument 'ignore_few_rounds'

----------------------------------------------------------------------
Ran 156 tests in 21.618s

FAILED (errors=1)
```
That was with 3.1.2.

### LINKED ISSUE #993: unhashable type: 'Ed25519Key'
Hi, after updating to Paramiko 2.2.0 some code that previously worked is now broken. I have minimized the reproduction code. Of course, I might have overly minimized it (removed the actual SSH key) because it can't work as is.

```python
import paramiko

ssh = paramiko.SSHClient()
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
ssh.load_system_host_keys()
ssh.connect('127.0.0.1')
```
```
Traceback (most recent call last):
  File "bis.py", line 6, in <module>
    ssh.connect('127.0.0.1')
  File "/tmp/paramiko/paramiko/client.py", line 377, in connect
    if our_key != server_key:
  File "/tmp/paramiko/paramiko/pkey.py", line 113, in __eq__
    return hash(self) == hash(other)
TypeError: unhashable type: 'Ed25519Key'
```

*known_hosts* (fake redacted hash):
```
127.0.0.1 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEZfTeFXnDtkVUYDWL0HiAL8+dXRpxuNpoNsYW1SkpRQ
```

Bisect:
> b395444062e82953d417a4da9157667c2e05d758 is the first bad commit

In older versions this code produces the following error:
```
paramiko.ssh_exception.SSHException: No authentication methods available
```

### PR DESCRIPTION
**Pull request by ploxiln**
fixes #990 
fixes #993 

cc @alex @bitprophet

### CODE REVIEW

**Comment by bitprophet** [comment]
FInally, a situation in which I can actualy use the 'change base' button without it massively screwing everything up! 😩 👌

**Comment by ploxiln** [comment]
Added changelog.

Yup, intended to base on 2.2, forgot when opening the PR, thanks :)
